### PR TITLE
fix: make noble addres selectable

### PR DESCRIPTION
**Pull request by rosepuppy**
Screenshot 2024-05-07 at 10 16 00 AM

### CODE REVIEW

**Review by jaredvu — APPROVED** [review]
toight. I think we could also we add an `allowUserSelect` prop

**Comment by rosepuppy** [comment]
>toight. I think we could also we add an allowUserSelect prop

oh good call, updated

**Review by yogurtandjam — APPROVED** [review]
can we use the `<CopyButton />` component for this?

happy to stamp though to unblock since this is a pretty annoying bug

**Comment by rosepuppy** [comment]
>can we use the `<CopyButton />` component for this?

We do use CopyButton the main CTA, that is intended use. I think this just incase the use wanna select the address directly

**Pull request merged**
