### PR TITLE
chore: Use new URL for Apybara API proxy in testnet

### PR DESCRIPTION
**Pull request by pswies**
Use the new API proxy with client-dedicated CORS setup.

### CODE REVIEW

**Comment by pswies** [comment]
Please do not merge yet. The proxy is buggy. Will ping when fixed.

**Comment by pswies** [comment]
The bug in API proxy has been fixed. This change is ready to go.

**Comment by tyleroooo** [comment]
On testnet I see requests failing with 502 bad gateway or stalling or getting 204 No Content

**Comment by pswies** [comment]
@tyleroooo Can you be more specific please? Both:
```
curl 'https://apybara-proxy-web-testnet.infrastructure-34d.workers.dev/v0/protocols/dydx'
```
and
```
curl 'https://apybara-proxy.infrastructure-34d.workers.dev/v0/protocols/dydx'
```
return the same result: 200 OK and some JSON content. Moreover, `apybara-proxy-web-testnet` is configured with CORS allowed origin as: `https://v4.testnet.dydx.exchange` so if you tested this in a Vercel preview, having another domain, it is the correct behavior if it fails.

**Comment by tyleroooo** [comment]
Ah yeah we tested on vercel

**Review by yogurtandjam — APPROVED** [review]

**Pull request merged**
